### ISSUE TITLE
如何在helm install 的时候指定CPU、内存、存储大小？

### ISSUE THREAD

**Issue by liushifa** [radondb/radondb-clickhouse-kubernetes#10]
如何在helm install 的时候指定CPU、内存、存储大小？

**Comment by su-houzhen** [comment]
can use `helm install --set key1=value1 --set key2=value2 --set ......` to customize the parameters

like `helm install clickhouse ck/clickhouse-cluster -n clickhouse --set clickhouse.resources.cpu=2 --set clickhouse.resources.memory=4Gi`

Configurable parameters refer to https://github.com/radondb/radondb-clickhouse-kubernetes/blob/main/document/deploy_radondb-clickhouse_operator_on_kubernetes.md#configuration

**Comment by su-houzhen** [comment]
If you need to customize too many parameters, you can use the following methods:
1. Download the `values.yaml` file in the helm chart
2. Modify the values in `values.yaml` as needed
3. use `helm install ... -f /path/to/values.yaml`

**Comment by liushifa** [comment]
好的。谢谢。
