### ISSUE TITLE
你好，请问如何获取arm架构的docker镜像包，或者提供自行构建的dockerfile？

### ISSUE THREAD

**Issue by fengallan0** [radondb/radondb-clickhouse-kubernetes#17]
你好，请问如何获取arm架构的docker镜像包，或者提供自行构建的dockerfile？

**Comment by su-houzhen** [comment]
目前没有构建 ARM 的镜像，这里是之前构建镜像使用的 dockerfile https://github.com/radondb/radondb-clickhouse-operator/tree/master/dockerfile，可以参考一下。

**Comment by fengallan0** [comment]
好的，谢谢
